[TC-1968] Add set_default functionality to gem
TerraCycle/spree-multi-domain pull request #3
Opened 2019-12-10 20:03 UTC by adamFoldvari

2019-12-11 12:39 UTC, SkayHUN approved these changes

2019-12-16 10:32 UTC, storhet requested changes

2019-12-16 10:32 UTC, storhet commented on config/routes.rb
> +Spree::Core::Engine.routes.draw do
```suggestion
Spree::Core::Engine.add_routes do
```

2019-12-17 09:39 UTC, storhet approved these changes

2019-12-17 09:40 UTC, merged