[TC-2051] Fix Spree 4.0 changes
TerraCycle/spree-multi-domain pull request #4
Opened 2020-01-20 13:58 UTC by erik-terracycle

2020-01-21 09:45 UTC, SkayHUN commented on spec/controllers/spree/admin/stores_controller_spec.rb
> +equire 'spec_helper'
typo

2020-01-21 09:51 UTC, SkayHUN commented on spec/controllers/spree/admin/stores_controller_spec.rb
> -  context 'update' do
did we remove this part intentionally?

2020-01-21 10:04 UTC, SkayHUN requested changes
check comments

2020-01-21 10:12 UTC, erik-terracycle commented on spec/controllers/spree/admin/stores_controller_spec.rb
> -  context 'update' do
yes

2020-01-22 11:11 UTC, SkayHUN approved these changes

2020-01-22 13:25 UTC, adamFoldvari approved these changes

2020-01-23 10:15 UTC, AHolcsik approved these changes

2020-01-23 10:59 UTC, VasiliyMaksymov approved these changes

2020-01-23 12:44 UTC, p0lish approved these changes

2020-01-23 13:08 UTC, storhet approved these changes

2020-01-29 08:13 UTC, bluta approved these changes

2020-01-29 08:13 UTC, merged